### ISSUE TITLE
Bug: App resets window location per item search. 

### ISSUE THREAD

**Issue by KewkLW** [Sidekick-Poe/Sidekick#389] opened 2024-12-25 16:01 UTC
Steps to reproduce: 

1. ctrl+d on any item. 
2. Drag window to secondary monitor. 
3. ctrl+d another item. 

Result: Window will revert back to the window where the game is running. 

Expected result: Window will update at current location.

**Comment by leMicin** [comment] 2024-12-25 16:02
Duplicate of #341

**Closed by leMicin** 2024-12-25 16:02 UTC
