### ISSUE TITLE
Initialization bug - Application stays in background without tray icon if the trade api is down during init

### ISSUE THREAD

**Issue by domialex** [Sidekick-Poe/Sidekick#276] opened 2024-12-15 16:37 UTC

**Comment by Dylgod** [comment] 2024-12-15 18:44
same for me

**Comment by Acrilik** [comment] 2024-12-15 22:44
same here

**Comment by Acrilik** [comment] 2024-12-15 23:24
installed microsoft edge and Microsoft Edge WebView2
that soled my problem

**Comment by leMicin** [comment] 2024-12-18 17:01
Duplicate of #322

**Closed by leMicin** 2024-12-18 17:01 UTC
