### ISSUE TITLE
Add support for regex shortcuts.

### ISSUE THREAD

**Issue by frgmnt** [Sidekick-Poe/Sidekick#435] opened 2024-12-30 10:58 UTC
It would be nice if there was some way to easily input various saved regex search terms. When I'm rolling waystones, I do it in bulk and dump them into a tab, search regex of dangerous mods so I can remove the dangerous ones from my pool. Currently I'm just copying/pasting the regex from the map check settings, but it would be nice if there was a streamlined way to do this in-game.

**Comment by leMicin** [comment] 2024-12-30 16:06
Thanks for the suggestion
This is a duplicate of #146

**Closed by leMicin** 2024-12-30 16:06 UTC
