### ISSUE TITLE
Add rounding for numbers

### ISSUE THREAD

**Issue by Igor-ua** [Sidekick-Poe/Sidekick#379] opened 2024-12-23 22:27 UTC
This would look better with the basic rounding

![Screenshot_220](https://github.com/user-attachments/assets/d79e1f48-2c82-45d4-9d28-a82cd7c03214)

**Comment by domialex** [comment] 2024-12-23 22:29
Duplicate of #330

**Closed by domialex** 2024-12-23 22:29 UTC
