### ISSUE TITLE
Error: Failed to load league data

### ISSUE THREAD

**Issue by hokq** [Sidekick-Poe/Sidekick#318] opened 2024-12-17 22:52 UTC
![Screenshot 2024-12-17 175114](https://github.com/user-attachments/assets/7a235d1b-9763-4608-870f-fe9e3c861828)

Sidekick was working fine until today. Reinstalled the program and still having the same issue. Any ideas and what steps I need to follow to resolve this error?

**Comment by domialex** [comment] 2024-12-17 22:53
Duplicate of #316

**Closed by domialex** 2024-12-17 22:53 UTC
