### ISSUE TITLE
(bug?) sidekick searches mods by "count", not "and"

### ISSUE THREAD

**Issue by crosscutsaw** [Sidekick-Poe/Sidekick#143] opened 2023-10-06 18:15 UTC
hello,

i think i catched a little bug. as you can see in pictures, sidekick searches mods by "count", not "and". it makes the other mod in results not even used. i think search logic should be fixed because of this.

https://imgur.com/a/scz1hLK

thanks

**Comment by leMicin** [comment] 2023-10-06 18:19
This is intended behavior due to how some of the mods work. We will see how we can adjust the logic to fix this scenario.

**Comment by leMicin** [comment] 2023-10-07 00:46
In the settings, can you try clicking Reset Cache and see if the problem still happens for you?

**Comment by crosscutsaw** [comment] 2023-10-07 12:40
> In the settings, can you try clicking Reset Cache and see if the problem still happens for you?

yes, with more entries
https://i.imgur.com/VwwVDG4.png

**Comment by leMicin** [comment] 2023-10-07 13:22
Thanks for those checks. Can you paste the watcher's eye item here? Ctrl+C in game and you can paste the item here.
Also just to confirm, you are using version 2.9.1?

**Comment by crosscutsaw** [comment] 2023-10-07 13:26
> Thanks for those checks. Can you paste the watcher's eye item here? Ctrl+C in game and you can paste the item here. Also just to confirm, are you using version 2.9.1?

you're welcome. yes, i'm using 2.9.1.

Item Class: Jewels
Rarity: Unique
Watcher's Eye
Prismatic Jewel
--------
Limited to: 1
--------
Item Level: 85
--------
5% increased maximum Energy Shield
4% increased maximum Life
6% increased maximum Mana
7% additional Physical Damage Reduction while affected by Determination
+12% chance to Suppress Spell Damage while affected by Grace
--------
One by one, they stood their ground against a creature 
they had no hope of understanding, let alone defeating,
and one by one, they became a part of it.
--------
Place into an allocated Jewel Socket on the Passive Skill Tree. Right click to remove from the Socket.
--------
Note: ~price 10 divine

**Comment by leMicin** [comment] 2023-10-22 22:20
I think this will be fixed in v2.10
Please try again in the next version (will be released in a few hours).
If the issue still happens, reopen this ticket (or create a new one).

**Closed by leMicin** 2023-10-22 22:20 UTC
Labels: bug
