### ISSUE TITLE
Chat commands are different for PoE2

### ISSUE THREAD

**Issue by domialex** [Sidekick-Poe/Sidekick#263] opened 2024-12-13 23:08 UTC
There is no distinction between `to` and `from` in the logs for PoE2, for unknown reasons.
PoE2:
```
2024/12/13 18:00:54 29126453 3ef2336d [INFO Client 17856] @xxx: test test
2024/12/13 18:04:04 29316421 3ef2336d [INFO Client 17856] @xxx: test
```

PoE1:
```
2024/12/11 10:18:45 326447218 cff94598 [INFO Client 37516] @From xxx: test
```

**Comment by leMicin** [comment] 2024-12-20 16:11
Duplicate of #340

**Closed by leMicin** 2024-12-20 16:11 UTC
Labels: Type: Bug, Status: Available, Priority: High
