### ISSUE TITLE
[BUG] [Trade API] Could not understand the API response.

### ISSUE THREAD

**Issue by akzhol0921** [Sidekick-Poe/Sidekick#304] opened 2024-12-17 05:00 UTC
Trying to use price check in Path of exile 2, game language is traditional chinese and standard league.
when trying to check the price it shows:
![image](https://github.com/user-attachments/assets/275609f1-7e1e-409d-88e6-ff4dc4246de8)
after a second it became:
![image](https://github.com/user-attachments/assets/2f8d8d59-b0b0-4200-9e4c-b8eca7e5b45f)

**Comment by leMicin** [comment] 2024-12-18 18:59
The http://www.pathofexile.tw/trade2/ website requires users to be logged in for the API to work. This is different than how the other APIs work. This is unfortunate, we may not be able to do something quickly to support that trade site.

**Comment by leMicin** [comment] 2024-12-18 19:01
Related to #323

**Comment by leMicin** [comment] 2024-12-18 19:03
Related to #324

**Comment by leMicin** [comment] 2024-12-19 00:28
Duplicate of #274

**Closed by leMicin** 2024-12-19 00:28 UTC
Labels: Type: Bug, Status: Available, Priority: Low
