### ISSUE TITLE
an exception error

### ISSUE THREAD

**Issue by majky666** [Sidekick-Poe/Sidekick#331] opened 2024-12-18 23:19 UTC
when I keep sidekick active and going to turn off computer, always this error meaasage window pops up:
An unknown software exception (0xe0434352) occurred in the application at location "0x00007ffa75ad837a"
Need press ok button to turn off computer.

**Comment by domialex** [comment] 2024-12-18 23:20
Thanks, it's a duplicate of #293

**Closed by domialex** 2024-12-18 23:20 UTC
